/*----- PROTECTED REGION ID(TangoLearn1Class.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TangoLearn1Class.cpp
//
// description : C++ source for the TangoLearn1Class class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TangoLearn1Class are implemented in this file.
//
// project :     Tango Learn 1 Class--Product Title
//
//
// Tango Learn 1Class Class--Class Copyright
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TangoLearn1Class.h>
#include <TangoLearn1ClassClass.h>

/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class.cpp

/**
 *  TangoLearn1Class class description:
 *    Tango Learn 1 Class--Class Description
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name           |  Method name
//================================================================
//  State                  |  Inherited (no method)
//  Status                 |  Inherited (no method)
//  tango_learn1_command1  |  tango_learn1_command1
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  tango_learn1_attribute1  |  Tango::DevDouble	Scalar
//  tango_learn1_attribute2  |  Tango::DevString	Scalar
//================================================================

namespace TangoLearn1Class_ns
{
/*----- PROTECTED REGION ID(TangoLearn1Class::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::TangoLearn1Class()
 *	Description : Constructors for a Tango device
 *                implementing the classTangoLearn1Class
 */
//--------------------------------------------------------
TangoLearn1Class::TangoLearn1Class(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::constructor_1
}
//--------------------------------------------------------
TangoLearn1Class::TangoLearn1Class(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::constructor_2
}
//--------------------------------------------------------
TangoLearn1Class::TangoLearn1Class(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TangoLearn1Class::delete_device()
{
	DEBUG_STREAM << "TangoLearn1Class::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::delete_device
	CORBA::string_free(*attr_tango_learn1_attribute2_read);
	delete[] attr_tango_learn1_attribute1_read;
	delete[] attr_tango_learn1_attribute2_read;
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void TangoLearn1Class::init_device()
{
	DEBUG_STREAM << "TangoLearn1Class::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_tango_learn1_attribute1_read = new Tango::DevDouble[1];
	attr_tango_learn1_attribute2_read = new Tango::DevString[1];
	/*----- PROTECTED REGION ID(TangoLearn1Class::init_device) ENABLED START -----*/
	
	// set an intial value for the attributes
	attr_tango_learn1_attribute1_read[0] = -1.0;
	attr_tango_learn1_attribute2_read[0] = Tango::string_dup("initial value");

	//	Initialize device

	DEBUG_STREAM << "TangoLearn1Class::init_device() protected initialization for device " << device_name << endl;
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::init_device
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void TangoLearn1Class::get_device_property()
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("tango_learn1_device_property1"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on TangoLearn1ClassClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		TangoLearn1ClassClass	*ds_class =
			(static_cast<TangoLearn1ClassClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize tango_learn1_device_property1 from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  tango_learn1_device_property1;
		else {
			//	Try to initialize tango_learn1_device_property1 from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  tango_learn1_device_property1;
		}
		//	And try to extract tango_learn1_device_property1 value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  tango_learn1_device_property1;

	}

	/*----- PROTECTED REGION ID(TangoLearn1Class::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void TangoLearn1Class::always_executed_hook()
{
	DEBUG_STREAM << "TangoLearn1Class::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TangoLearn1Class::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TangoLearn1Class::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void TangoLearn1Class::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TangoLearn1Class::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute tango_learn1_attribute1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TangoLearn1Class::read_tango_learn1_attribute1(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TangoLearn1Class::read_tango_learn1_attribute1(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::read_tango_learn1_attribute1) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_tango_learn1_attribute1_read);
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::read_tango_learn1_attribute1
}
//--------------------------------------------------------
/**
 *	Write attribute tango_learn1_attribute1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TangoLearn1Class::write_tango_learn1_attribute1(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TangoLearn1Class::write_tango_learn1_attribute1(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TangoLearn1Class::write_tango_learn1_attribute1) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::write_tango_learn1_attribute1
}
//--------------------------------------------------------
/**
 *	Read attribute tango_learn1_attribute2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TangoLearn1Class::read_tango_learn1_attribute2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TangoLearn1Class::read_tango_learn1_attribute2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::read_tango_learn1_attribute2) ENABLED START -----*/
	//	Set the attribute value
	
	CORBA::string_free(*attr_tango_learn1_attribute2_read);
	attr_tango_learn1_attribute2_read[0] = Tango::string_dup("interrogated value");
  attr.set_value(attr_tango_learn1_attribute2_read);
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::read_tango_learn1_attribute2
}
//--------------------------------------------------------
/**
 *	Write attribute tango_learn1_attribute2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TangoLearn1Class::write_tango_learn1_attribute2(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TangoLearn1Class::write_tango_learn1_attribute2(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);

	/*----- PROTECTED REGION ID(TangoLearn1Class::write_tango_learn1_attribute2) ENABLED START -----*/

	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::write_tango_learn1_attribute2
}

//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TangoLearn1Class::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command tango_learn1_command1 related method
 *	Description: Tango Learn1 Command1
 *
 */
//--------------------------------------------------------
void TangoLearn1Class::tango_learn1_command1()
{
	DEBUG_STREAM << "TangoLearn1Class::tango_learn1_command1()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TangoLearn1Class::tango_learn1_command1) ENABLED START -----*/
	
	INFO_STREAM << "TangoLearn1Class::tango_learn1_command1()  - " << device_name << endl;
	push_data_ready_event("tango_learn1_attribute1", 1234);
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::tango_learn1_command1
}
//--------------------------------------------------------
/**
 *	Method      : TangoLearn1Class::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void TangoLearn1Class::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(TangoLearn1Class::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::add_dynamic_commands
}

/*----- PROTECTED REGION ID(TangoLearn1Class::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TangoLearn1Class::namespace_ending
} //	namespace
