/*----- PROTECTED REGION ID(TangoLearn1ClassClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        TangoLearn1ClassClass.h
//
// description : Include for the TangoLearn1Class root class.
//               This class is the singleton class for
//                the TangoLearn1Class device class.
//               It contains all properties and methods which the 
//               TangoLearn1Class requires only once e.g. the commands.
//
// project :     Tango Learn 1 Class--Product Title
//
//
// Tango Learn 1Class Class--Class Copyright
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TangoLearn1ClassClass_H
#define TangoLearn1ClassClass_H

#include <tango.h>
#include <TangoLearn1Class.h>


/*----- PROTECTED REGION END -----*/	//	TangoLearn1ClassClass.h


namespace TangoLearn1Class_ns
{
/*----- PROTECTED REGION ID(TangoLearn1ClassClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	TangoLearn1ClassClass::classes for dynamic creation

//=========================================
//	Define classes for commands
//=========================================
//	Command tango_learn1_command1 class definition
class tango_learn1_command1Class : public Tango::Command
{
public:
	tango_learn1_command1Class(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	tango_learn1_command1Class(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~tango_learn1_command1Class() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TangoLearn1Class *>(dev))->is_tango_learn1_command1_allowed(any);}
};


/**
 *	The TangoLearn1ClassClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  TangoLearn1ClassClass : public Tango::DeviceClass
#else
class TangoLearn1ClassClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(TangoLearn1ClassClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TangoLearn1ClassClass::Additionnal DServer data members

	//	Class properties data members
	public:
		//	tango_learn1_class_property1:	Tango Learn1 Class Property1--Description
		string	tango_learn1_class_property1;
		//	tango_learn1_class_property2:	Tango Learn1 Class Property2
		Tango::DevLong	tango_learn1_class_property2;
	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static TangoLearn1ClassClass *init(const char *);
		static TangoLearn1ClassClass *instance();
		~TangoLearn1ClassClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		TangoLearn1ClassClass(string &);
		static TangoLearn1ClassClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	TangoLearn1Class_H
